# Generated by Django 5.2.8 on 2025-12-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price must be greater than or equal to 0.', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current quantity in stock.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
